"""initial schema

Revision ID: 01f61bd5e042
Revises:
Create Date: 2026-08-10 01:19:05.739507
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '01f61bd5e042'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=False),
    sa.Column('after_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('baskets',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=False),
    sa.Column('target_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('cash_balance_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('emergency_target_cny', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('calculation_note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_code'), 'baskets', ['code'], unique=True)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('function_name', sa.String(length=80), nullable=False),
    sa.Column('input_mapping', sa.JSON(), nullable=False),
    sa.Column('output_mapping', sa.JSON(), nullable=False),
    sa.Column('packages', sa.JSON(), nullable=False),
    sa.Column('schedule_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=24), nullable=False),
    sa.Column('git_revision', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('target_amount_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reward_title', sa.String(length=160), nullable=False),
    sa.Column('reward_description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('achieved_snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_plans',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('amount_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('allocation_mode', sa.String(length=20), nullable=False),
    sa.Column('growth_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('risk_ratio', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_rules',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('metric_path', sa.String(length=160), nullable=False),
    sa.Column('operator', sa.String(length=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('headers_json', sa.JSON(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('max_deliveries', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_tasks',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_tasks_kind'), 'pending_tasks', ['kind'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('total_asset_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('principal_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('profit_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('basket_values', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_observed_at'), 'portfolio_snapshots', ['observed_at'], unique=False)
    op.create_table('assets',
    sa.Column('basket_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('units', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fx_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_source', sa.String(length=40), nullable=False),
    sa.Column('source_attributes', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_basket_id'), 'assets', ['basket_id'], unique=False)
    op.create_table('data_source_runs',
    sa.Column('data_source_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_runs_data_source_id'), 'data_source_runs', ['data_source_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_excerpt', sa.Text(), nullable=False),
    sa.Column('suppressed_reason', sa.String(length=120), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['notification_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_deliveries_delivered_at'), 'notification_deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_event_key'), 'notification_deliveries', ['event_key'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_rule_id'), 'notification_deliveries', ['rule_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('basket_id', sa.String(length=36), nullable=True),
    sa.Column('destination_basket_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('units_delta', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reverses_entry_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['destination_basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_kind'), 'ledger_entries', ['kind'], unique=False)
    op.create_index(op.f('ix_ledger_entries_occurred_at'), 'ledger_entries', ['occurred_at'], unique=False)
    op.create_table('valuations',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('units', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('value_cny', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_asset_id'), 'valuations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_valuations_observed_at'), 'valuations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuations_observed_at'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_asset_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_ledger_entries_occurred_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_kind'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_notification_deliveries_rule_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_event_key'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_delivered_at'), table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_data_source_runs_data_source_id'), table_name='data_source_runs')
    op.drop_table('data_source_runs')
    op.drop_index(op.f('ix_assets_basket_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_portfolio_snapshots_observed_at'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_pending_tasks_kind'), table_name='pending_tasks')
    op.drop_table('pending_tasks')
    op.drop_table('notification_rules')
    op.drop_table('investment_plans')
    op.drop_table('goals')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_baskets_code'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
